### ISSUE TITLE
Just opening and issue here, as I cannot find your email address.

### ISSUE THREAD

**Issue by ghost** [wolfyzvf/Zimbra-Collaboration-Bash-Completion#2]
Just opening and issue here, as I cannot find your email address.

I just sent you an invite to join the Zeta Alliance Github organisation, and I also forked this repo there.

Hope we can work together on the Zeta Alliance Github , in the mean time, I am willing to test and push the bash completion work you did.

Did you update it for 8.8?

**Comment by wolfyzvf** [comment]
Hey Barry,

You should have received a mail from me. Tell me if it's not the case.

Best regards,
Wolfyxzvf
